#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
USE_PROCD=1

start_service() {
	/bin/setgateway.sh &
	/bin/tcptouart.sh &
	#mjpg_streamer  -i "input_uvc.so -d /dev/video0 -r 320x240 -f 30" -o "output_http.so -p 8181" &
	if [ -f /bin/rtspfileserver.sh ];then
		/bin/rtspfileserver.sh &
	fi
}
stop_service() {
        echo "stop my server"
	killall setgateway.sh
        killall tcptouart.sh tcptouart
}

